// Generated by prisma/post-generate.ts

import { Kysely } from "kysely";
import { PlanetScaleDialect } from "kysely-planetscale";
import { nanoid } from "nanoid";

import { ColumnType, Generated } from "kysely";

export type Post = {
  id: string;
  userId: string;
  title: string;
  content: string;
};

export type Database = {
  Post: Post;
};


export const db = new Kysely<Database>({
  dialect: new PlanetScaleDialect({
    url: process.env.DATABASE_URL,
  }),
});

export const genId = nanoid;
